version: "3"
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="people"
    ports:
      - 27017:27017
  #people-api:
  #  image: people-app-image
  #  container_name: people-api
  #  ports:
  #    - "3000:3000"
  #  restart: always
